services:
  sql:
    container_name: postgres
#    environment:
#      - PGDATA=/data/postgres
    build: ./p
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5332:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  postgres_data:
