@echo off
set PYTHONDONTWRITEBYTECODE=1
set PYTHONUTF8=1
set FLASK_APP=app.py
set FLASK_DEBUG=1
set FLASK_RUN_HOST=0.0.0.0
set FLASK_RUN_PORT=80
set WERKZEUG_DEBUG_PIN=off
D:\Software\flask\Scripts\flask.exe run