CREATE TABLE users
(
	id	INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	accuracy	INTEGER,
	family	TEXT,
	gender	INTEGER,
	location	POINT,
	mobile	TEXT ARRAY,
	name	TEXT,
	password	TEXT,
	role	INTEGER,
	user_name	TEXT
);
CREATE TABLE shops
(
	id	INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	accuracy	INTEGER,
	address	TEXT,
	description	TEXT,
	location	POINT,
	multiplier	REAL,
	phones	TEXT ARRAY,
	photos	TEXT ARRAY,
	title	TEXT,
 	owner	INTEGER
);
CREATE TABLE services
(
	id	INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	description	TEXT,
	duration	INTEGER,
	photos	TEXT ARRAY,
	price	INTEGER
);
CREATE TABLE proficiencies
(
	barber	INTEGER,
	quality	INTEGER,
	service	INTEGER
);
CREATE TABLE votes
(
	id	INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	barber	INTEGER,
	comment	TEXT,
	customer	INTEGER,
	score	INTEGER,
	time	TIMESTAMP
);
CREATE TABLE requests
(
	id	INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	barber	INTEGER,
	customer	INTEGER,
	note	TEXT,
	service	INTEGER,
	time	TIMESTAMP
);
CREATE TABLE products
(
	id	INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	description	TEXT,
	photos	TEXT ARRAY,
	price	INTEGER
);
CREATE TABLE attributes
(
	title	TEXT PRIMARY KEY,
	dimension	INTEGER,
	icon	TEXT,
	type	INTEGER
);
CREATE TABLE translations
(
	id	TEXT PRIMARY KEY,
	en	TEXT,
	fa	TEXT
);
