name: ساخت دوباره
on: [push]
jobs:
  deploy:
    name: به روز رسانی نرم افزار
    runs-on: ubuntu-latest
    steps:
      - name: ساخت پوشه‌ای برای نوشتن کلیدها
        run: mkdir -m 700 ~/.ssh
          
      - name: نوشتن کلیدها
        run: |
          cd  ~/.ssh
          echo "${{secrets.PRIVATE_KEY}}" > id_ed25519
          sudo chmod 600 id_ed25519
          echo "${{secrets.KNOWN_HOSTS}}" > known_hosts

      - name: پیوستن به دستگاه پایانی
        run: |
          ssh -p ${{secrets.PORT}} ${{secrets.USER}}@${{secrets.SERVER}} "rebuild.sh"
