name: ساخت دوباره
on: [push]
jobs:
  deploy:
    name: به روز رسانی نرم افزار
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ~/.ssh

    before:
      run: mkdir ~/.ssh

    steps:
      - name: ساخت پوشه‌ای برای نوشتن کلید پنهان
        run: |
          pwd
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          
      - name: نوشتن کلید پنهان
        run: |
          pwd
          cd  ~/.ssh
          echo "${{secrets.PRIVATE_KEY}}" > id_ed25519
          sudo chmod 600 id_ed25519
          
      - name: نوشتن کلید آشکار دستگاه‌ها
        run: |
          pwd
          cd  ~/.ssh
          echo "${{secrets.KNOWN_HOSTS}}" > known_hosts

      - name: پیوستن به دستگاه پایانی
        run: |
          ssh -p ${{secrets.PORT}} ${{secrets.USER}}@${{secrets.SERVER}} "cd ${{secrets.APP_FOLDER}} && git pull"
