name: ساخت دوباره
on: [push]
jobs:
  deploy:
    name: به روز رسانی نرم افزار
    runs-on: ubuntu-latest
    steps:
      - name: ساخت پوشه‌ای برای نوشتن کلید پنهان
        run: mkdir ~/.ssh

      - name: نوشتن کلید پنهان
        run: echo "${{secrets.PRIVATE_KEY}}" > ~/.ssh/id_ed25519

      - name: نوشتن کلید آشکار دستگاه‌ها
        run: echo "${{secrets.KNOWN_HOSTS}}" > ~/.ssh/known_hosts

      - name: پیوستن به دستگاه پایانی
        run: |
          ssh -p ${{secrets.PORT}} ${{secrets.USER}}@${{secrets.SERVER}} "cd ${{secrets.APP_FOLDER}} && bash rebuild"