name: ساخت دوباره
on: [push]
jobs:
  deploy:
    name: به روز رسانی نرم افزار
    runs-on: ubuntu-latest
    environment:
      SSH: ~/.ssh
    steps:
      - name: ساخت پوشه‌ای برای نوشتن کلید پنهان
        run: |
          mkdir $SSH
          chmod 600 $SSH

      - name: نوشتن کلید پنهان
        run: |
          cd  $SSH
          echo "${{secrets.PRIVATE_KEY}}" > id_ed25519
          chmod 600 id_ed25519

      - name: نوشتن کلید آشکار دستگاه‌ها
        run: |
          cd  $SSH
          echo "${{secrets.KNOWN_HOSTS}}" > known_hosts

      - name: پیوستن به دستگاه پایانی
        run: |
          ssh -p ${{secrets.PORT}} ${{secrets.USER}}@${{secrets.SERVER}} "cd ${{secrets.APP_FOLDER}} && bash rebuild.sh"
