name: Deploy 🚀
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: SSH Deploy
        run: |
          mkdir ~/.ssh
          echo "$secrets.USER"@"$secrets.SERVER"
          echo secrets.SERVER
          echo "$secrets.PRIVATE_KEY" > ~/.ssh/id_ed25519
          sudo chmod 600 ~/.ssh/id_ed25519
          echo "$secrets.KNOWN_HOSTS" > ~/.ssh/known_hosts
          ssh "$secrets.USER"@"$secrets.SERVER"
          mkdir aaaaaa
          echo "Successfully pulled repo."
        shell: bash
