name: ساخت دوباره
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ~/.ssh
    steps:
      - name: ساخت پوشه‌ای برای گذاشتن کلید‌ها
        run: |
          mkdir $folder
          cd $folder
      - name: نوشتن کلیدها
        run: |
          echo "${{secrets.PRIVATE_KEY}}" > id_ed25519
          sudo chmod 600 id_ed25519
          echo "${{secrets.KNOWN_HOSTS}}" > known_hosts
      - name: پیوستن به دستگاه پایانی
        run: |
          ssh -p "${{secrets.PORT}}" "${{secrets.USER}}"@"${{secrets.SERVER}}" "mkdir /home/ghasem/aaaaaa && whoami"
          echo "Successfully pulled repo."
